FROM node:20.13.1-alpine
# FROM node:20.13.1 as build

WORKDIR /app

COPY package*.json /app/
RUN ["npm", "install"]
COPY . /app/
RUN npm run build

# FROM node:20.13.1-alpine AS release
# WORKDIR /release

# COPY package*.json /
# RUN ["npm", "install", "--registry=http://r.tnpm.oa.com", "--production"]

# 移入依赖与源码
# COPY --from=build /app/dist /release/dist

# 启动服务
EXPOSE 3000

CMD ["node", "./dist/main.js"]

